version: "3.8"
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile.Dev
    ports:
      - 8080:8080
    working_dir: /app
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app
